package exporter

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"ai_agent_termux/database"
)

// ObsidianExporter exports summaries to Obsidian vault
type ObsidianExporter struct {
	vaultPath string
	db        *database.Database
}

// NewObsidianExporter creates an exporter instance
func NewObsidianExporter(vaultPath string, db *database.Database) *ObsidianExporter {
	return &ObsidianExporter{
		vaultPath: vaultPath,
		db:        db,
	}
}

// ExportAll exports all document summaries as Markdown notes
func (oe *ObsidianExporter) ExportAll() error {
	docs, err := oe.db.GetAllDocuments()
	if err != nil {
		return err
	}

	exportDir := filepath.Join(oe.vaultPath, "G.I.D.A", "Summaries")
	os.MkdirAll(exportDir, 0755)

	for _, doc := range docs {
		if err := oe.exportDocument(doc, exportDir); err != nil {
			continue // Skip failed exports
		}
	}

	return nil
}

func (oe *ObsidianExporter) exportDocument(doc database.Document, exportDir string) error {
	// Create sanitized filename
	basename := filepath.Base(doc.Path)
	noteName := strings.ReplaceAll(basename, " ", "_")
	notePath := filepath.Join(exportDir, noteName+".md")

	// Build Markdown content
	var content strings.Builder
	content.WriteString(fmt.Sprintf("# %s\n\n", basename))
	content.WriteString(fmt.Sprintf("> **Source:** `%s`\n", doc.Path))
	content.WriteString(fmt.Sprintf("> **Type:** %s\n", doc.FileType))
	content.WriteString(fmt.Sprintf("> **Indexed:** %s\n\n", doc.LastIndexed.Format(time.RFC3339)))
	content.WriteString("## Summary\n\n")
	content.WriteString(doc.Summary + "\n\n")
	content.WriteString("---\n")
	content.WriteString("*Generated by G.I.D.A (Generalized Intelligent Data Agent)*\n")

	return os.WriteFile(notePath, []byte(content.String()), 0644)
}
